import TopButtonBar from "./TopButtonBar.jsx";
import NavigationBar from "./NavigationBar.jsx";
import Entries from "./Entries.jsx";
import BottomButtonBar from "./BottomButtonBar.jsx";
import Downloads from "./Downloads.jsx";
import InfoBar from "./InfoBar.jsx";
import DialogsContainer from "./DialogsContainer.jsx";

function ZipManagerView({ state, ui, actions }) {
  const {
    appClassName,
    entries,
    selectedFolder,
    highlightedIds,
    entriesElementHeight,
    entriesDeltaHeight,
    highlightedEntryElementRef,
    entriesElementRef,
    downloads,
    dialogs,
    clickedButtonName,
    theme,
    musicData,
    playerActive
  } = state;
  const {
    constants,
    messages,
    i18n,
    disabledExportZip,
    disabledReset,
    disabledBack,
    disabledForward,
    disabledCopy,
    disabledCut,
    disabledPaste,
    disabledResetClipboardData,
    disabledHighlightAll,
    disabledExtract,
    disabledRename,
    disabledDelete,
    hiddenNavigationBar,
    hiddenDownloadManager,
    hiddenInfobar,
    hiddenExportPassword,
    ancestorFolders
  } = ui;
  const {
    openPromptCreateFolder,
    importZipFile,
    openPromptExportZip,
    openConfirmReset,
    openOptions,
    showImportZipFilePicker,
    showAddFilesPicker,
    resetClickedButtonName,
    navigateBack,
    navigateForward,
    goIntoFolder,
    dropFiles,
    highlight,
    handleToggleEntry,
    toggleRange,
    enterEntry,
    updateEntriesHeightWithElement,
    updateEntriesElementHeight,
    registerResizeEntriesHandlerWithElement,
    copy,
    cut,
    paste,
    resetClipboardData,
    extract,
    highlightAll,
    openPromptRename,
    openConfirmDeleteEntries,
    resizeEntries,
    updateEntriesElementHeightEndWithElement,
    abortDownload,
    playMusic,
    stopMusic,
    setTheme,
    createFolder,
    closePromptCreateFolder,
    exportZip,
    closePromptExportZip,
    closePromptExtract,
    rename,
    closePromptRename,
    reset,
    closeConfirmReset,
    deleteEntries,
    closeConfirmDeleteEntries,
    closeDisplayError,
    closePromptImportPassword,
    setOptions,
    resetOptions,
    closeOptions,
    addFiles,
    closeChooseAction
  } = actions;

  return (
    <div className={appClassName}>
      <main>
        <TopButtonBar
          disabledExportZipButton={disabledExportZip}
          disabledResetButton={disabledReset}
          clickedButtonName={clickedButtonName}
          onCreateFolder={openPromptCreateFolder}
          onImportZipFile={importZipFile}
          onExportZip={openPromptExportZip}
          onReset={openConfirmReset}
          onOpenOptions={openOptions}
          onShowImportZipFilePicker={showImportZipFilePicker}
          onShowAddFilesPicker={showAddFilesPicker}
          onClickedButton={resetClickedButtonName}
          constants={constants}
          messages={messages}
        />
        <NavigationBar
          selectedFolder={selectedFolder}
          ancestorFolders={ancestorFolders}
          disabledBackButton={disabledBack}
          disabledForwardButton={disabledForward}
          clickedButtonName={clickedButtonName}
          hidden={hiddenNavigationBar}
          onNavigateBack={navigateBack}
          onNavigateForward={navigateForward}
          onGoIntoFolder={goIntoFolder}
          onClickedButton={resetClickedButtonName}
          constants={constants}
          messages={messages}
        />
        <Entries
          entries={entries}
          selectedFolder={selectedFolder}
          highlightedIds={highlightedIds}
          entriesElementHeight={entriesElementHeight}
          deltaEntriesHeight={entriesDeltaHeight}
          hiddenDownloadManager={hiddenDownloadManager}
          onDropFiles={dropFiles}
          onHighlight={highlight}
          onToggle={handleToggleEntry}
          onToggleRange={toggleRange}
          onEnter={enterEntry}
          onUpdateEntriesHeight={updateEntriesHeightWithElement}
          onUpdateEntriesElementHeight={updateEntriesElementHeight}
          onRegisterResizeEntriesHandler={registerResizeEntriesHandlerWithElement}
          entriesElementRef={entriesElementRef}
          highlightedEntryElementRef={highlightedEntryElementRef}
          i18n={i18n}
          constants={constants}
          messages={messages}
        />
        <BottomButtonBar
          disabledCopyButton={disabledCopy}
          disabledCutButton={disabledCut}
          disabledPasteButton={disabledPaste}
          disabledResetClipboardDataButton={disabledResetClipboardData}
          disabledExtractButton={disabledExtract}
          disabledHighlightAllButton={disabledHighlightAll}
          disabledRenameButton={disabledRename}
          disabledDeleteButton={disabledDelete}
          clickedButtonName={clickedButtonName}
          onCopy={copy}
          onCut={cut}
          onPaste={paste}
          onResetClipboardData={resetClipboardData}
          onExtract={extract}
          onHighlightAll={highlightAll}
          onRename={openPromptRename}
          onRemove={openConfirmDeleteEntries}
          onMove={resizeEntries}
          onUpdateElementHeight={updateEntriesElementHeightEndWithElement}
          onClickedButton={resetClickedButtonName}
          constants={constants}
          messages={messages}
        />
        <Downloads
          downloads={downloads}
          hidden={hiddenDownloadManager}
          onAbortDownload={abortDownload}
          i18n={i18n}
          constants={constants}
          messages={messages}
        />
      </main>
      <InfoBar
        hidden={hiddenInfobar}
        theme={theme}
        musicData={musicData}
        playerActive={playerActive}
        onPlayMusic={playMusic}
        onStopMusic={stopMusic}
        onSetTheme={setTheme}
        constants={constants}
        messages={messages}
      />
      <DialogsContainer
        dialogs={dialogs}
        hiddenExportPassword={hiddenExportPassword}
        messages={messages}
        onCreateFolder={createFolder}
        onCloseCreateFolder={closePromptCreateFolder}
        onExportZip={exportZip}
        onCloseExportZip={closePromptExportZip}
        onExtract={extract}
        onCloseExtract={closePromptExtract}
        onRename={rename}
        onCloseRename={closePromptRename}
        onReset={reset}
        onCloseReset={closeConfirmReset}
        onDeleteEntries={deleteEntries}
        onCloseDeleteEntries={closeConfirmDeleteEntries}
        onCloseDisplayError={closeDisplayError}
        onCloseImportPassword={closePromptImportPassword}
        onSetOptions={setOptions}
        onResetOptions={resetOptions}
        onCloseOptions={closeOptions}
        onImportZipFile={importZipFile}
        onAddFiles={addFiles}
        onCloseChooseAction={closeChooseAction}
      />
    </div>
  );
}

export default ZipManagerView;
