#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE__BOOL 1
#define STDC_HEADERS 1
#define PACKAGE "libtfmxaudiodecoder"
#define PACKAGE_NAME "libtfmxaudiodecoder"
#define PACKAGE_VERSION "1.0.14"
#define VERSION "1.0.14"
